### ISSUE TITLE
some parameter issues

### ISSUE THREAD

**Issue by unknownfox71** [gregmoille/pyLLE#24]
Hello
l have successfully run the code, but, i have some confusion about parameter you setting in ComputeLLE.jl

- why the loss(α) and coupling(θ), and detuning range(δω), both multiplied by a tR, the round trip time? it that every round trip we need to get a total loss?
- the energy, both noise and the input pumping light, times the length of mode(length(μ)), every trip, the energy is not the just Ein, rather in each mode there is an Ein?
- and the dt = 0.1/(sqrt(Pin)), i have no idea that, dt is related to power. and in your code, is dt the step length in split Fourier method?

Thanks for your answer. Kind regards,
LiChenhong

**Comment by gregmoille** [comment]
Hi, 

First of, that’s god news you manage to get the code runing 😊

- The multiplication by the round trip is one way to obtain a normalized equation, where all the component in Hz are multiplied by it, the integrated dispersion too if I remember correctly, and the other components are implicitly. This is not the standard normalization by the loss (where the loss could actually be spectrally dépendant and such normalization can be an issue), but this is one way to do it lower values for all this angular frequency that are >10^9  and needs to be reduced for stabilization. 
- Energy, noise and the driving force are in the spectral domain, the LLE is a temporal solver. Therfore a iFFT has to be applied on these components. However, Julia applies a normalization (I think Matlab too) by the length of the array. This normalisation which is the size of the spectral array is there to compensate for this
- The LLE stabilization scales with the energy inside the resonator, therefore the driving field energy. It is nasty for sure to have coded it this way but this is so far the only way I found it to avoid an adaptative SSF step size.

**Comment by unknownfox71** [comment]
Hello,
Thank you so much, and I checked that the integrated dispersion is indeed mutiplied by tR, and, i just finded that before the iteration, the intergrated dispersion Dint*tR, and then divided by L, What is this mean? I mean, L is the length of cavity, why the normalized intergrated dispersion is divided by L. 
Thanks again.

**Comment by gregmoille** [comment]
Sorry about the confusion about the Dint normalize with the cavity length. 
Historically, there way I coded the core script was using the phase difference (or the β coefficient) instead of the integrated dispersion, which yields a slightly different formula than the Dint (see [line 107 of  _analysedisp.py](https://github.com/gregmoille/pyLLE/blob/1b90deb454abc616b7fc8742ac9c942aaf2d3eef/pyLLE/_analyzedisp.py#L107)). From the phase shift, one could easily extract the β, from which in the LLE the path length has to be taken into account. The funny thing is that the phase and β are the same except the normalisation of the length (see line [116 of the julia core](https://github.com/gregmoille/pyLLE/blob/1b90deb454abc616b7fc8742ac9c942aaf2d3eef/pyLLE/ComputeLLE.jl#L116) and the [line 206 ](https://github.com/gregmoille/pyLLE/blob/1b90deb454abc616b7fc8742ac9c942aaf2d3eef/pyLLE/ComputeLLE.jl#L206)). 
I agree this is a bit confusing and a new version of the code I am currently working on will clear up a lot of this mess, yet we are still in the process of publishing experimental/simulation results so I won’t push it on github just yet.
